---
- name: Copy kube-install.sh script to all hosts
  hosts: all

  tasks:
    - name: Copy kube-install.sh script
      become: false
      copy:
        src: ../script/kube-install.sh
        dest: ~/kube-install.sh
        mode: 0755

    - name: run kube-install
      become: true
      shell: |
        sudo ./kube-install.sh --command 2 --k8s-version 1.31.1 --endpoint 192.168.227.11

    # - name: run kube-install
    #   become: true
    #   shell: |
    #     sudo ./kube-install.sh --command 1 --k8s-version 1.31.1 --endpoint 10.227.0.10


    # - name: delete kube
    #   become: true
    #   shell: |
    #     sudo ./kube-install.sh --command 3 --k8s-version 1.31.1 --endpoint 10.227.0.10


